defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  host: <%= ENV["FLANG_MYSQL_HOST"] || "127.0.0.1" %>
  port: <%= ENV["FLANG_MYSQL_PORT"] || 3306 %>
  username: <%= ENV["FLANG_MYSQL_USERNAME"] || "root" %>
  password: <%= ENV["FLANG_MYSQL_PASSWORD"] || "root" %>
  database: <%= ENV["FLANG_MYSQL_DATABASE"] || "flang_#{Rails.env}" %>

development: *defaults
test: *defaults
production: *defaults
