defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5

development:
  database: "<%= ENV['FLANG_MYSQL_DEVELOPMENT_DATABASE'] %>"
  username: "<%= ENV['FLANG_MYSQL_DEVELOPMENT_USERNAME'] %>"
  password: "<%= ENV['FLANG_MYSQL_DEVELOPMENT_PASSWORD'] %>"
  host: "<%= ENV['FLANG_MYSQL_DEVELOPMENT_HOST'] %>"
  port: <%= ENV['FLANG_MYSQL_DEVELOPMENT_PORT'] %>
  <<: *defaults

test:
  database: "<%= ENV['FLANG_MYSQL_TEST_DATABASE'] %>"
  username: "<%= ENV['FLANG_MYSQL_TEST_USERNAME'] %>"
  password: "<%= ENV['FLANG_MYSQL_TEST_PASSWORD'] %>"
  host: "<%= ENV['FLANG_MYSQL_TEST_HOST'] %>"
  port: <%= ENV['FLANG_MYSQL_TEST_PORT'] %>
  <<: *defaults

production:
  database: "<%= ENV['FLANG_MYSQL_DATABASE'] %>"
  username: "<%= ENV['FLANG_MYSQL_USERNAME'] %>"
  password: "<%= ENV['FLANG_MYSQL_PASSWORD'] %>"
  host: "<%= ENV['FLANG_MYSQL_HOST'] %>"
  port: <%= ENV['FLANG_MYSQL_PORT'] || 3306 %>
  <<: *defaults
