defaults: &defaults
  host: <%= ENV["FLANG_MONGO_HOST"] || "127.0.0.1" %>
  port: <%= ENV["FLANG_MONGO_PORT"] || 27017 %>

development:  
  <<: *defaults
  database: flang_development

test:  
  <<: *defaults
  database: flang_test

production:  
  <<: *defaults
  database: <%= ENV["FLANG_MONGO_DATABASE"] || "flang" %>
  username: <%= ENV["FLANG_MONGO_USERNAME"] %>
  password: <%= ENV["FLANG_MONGO_PASSWORD"] %>
