<%
def process_mongo_database_uri(uri)
  if uri =~ %r{^mongodb://(?:([^:]*?)(?:\:(\S*?))?@)?([^:]*?)(?:\:(\d+))?/(\S+)$}i
    mongo = { :host => $~[3], :port => ($~[4] || 27017).to_i, :database => $~[5] }
    mongo[:username] = $~[1] if $~[1]
    mongo[:password] = $~[2] if $~[2]
    mongo
  else
    raise ArgumentError, "Invalid MongoDB URI (#{uri.inspect})"
  end
end
%>

defaults: &defaults
  host: 127.0.0.1
  port: 27017

development:
  <<: *defaults
  database: flang_development

test:
  <<: *defaults
  database: flang_test

<%
if Rails.env.to_s == "production"
  raise "Missing MONGODB_URI" unless ENV["MONGODB_URI"]
  production = process_mongo_database_uri(ENV["MONGODB_URI"])
%>
production:
  host: <%= production[:host] %>
  port: <%= production[:port] %>
  <% if production[:username] %>
  username: <%= production[:username] %>
  <% end %>
  <% if production[:password] %>
  password: <%= production[:password] %>
  <% end %>
  database: <%= production[:database] %>
<% end %>
